# https://taskfile.dev

version: '3'

vars:
  publicdir: public

tasks:
  run:
    cmds:
      - task: compile-sass
      - npm run dev
  build:
    cmds:
      - task: compile-sass
      - npm run build
  prepare:
    dir: ./dist
    cmds:
      - mv not_found/index.html not_found.html
      # Delete SCSS files
      - rm **/*.scss
      - rm *.scss
  publish:
    cmds:
      - neocities push dist
  build-publish:
    cmds:
      - task: build
      - task: prepare
      - task: publish
  compile-sass:
    cmds:
      - npx sass "{{.publicdir}}" -p node --no-source-map # source maps have impeded local dev
  serve:
    cmds:
      - python -m http.server -d dist 4321
  build-serve:
    cmds:
      - task: build
      - task: serve